"""Adicionando a coluna role em Users

Revision ID: ec0a60201a04
Revises: 8af7705440fe
Create Date: 2025-11-27 03:55:33.292851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0a60201a04'
down_revision: Union[str, None] = '8af7705440fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_cpf_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_cpf_key'), 'users', ['cpf'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
